version: "1.1.1-{build}"

branches:
  only:
    - master

os: Windows Server 2012 R2

environment:
  GOPATH: c:\gopath

init:
  - SET PATH=%GOPATH%\bin;%PATH%
  - git config --global core.autocrlf input

install:
  - go version
  - go env
  - mkdir %GOPATH%
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/tischda/go2xunit
  - go get -u github.com/tischda/timer/registry

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - go build -o timer.exe

test_script:
  - go test -v -cover
  - go test -v | go2xunit -xunitnet > xunit-report.xml
  - timer.exe -version
  - timer.exe start t1
  - timer.exe read t1
  - timer.exe start t2
  - timer.exe list
  - timer.exe stop t1
  - timer.exe clear
  - timer.exe exec "dir *.exe"
  - timer.exe help

artifacts:
  - path: timer.exe
    name: Timer

deploy: off

on_finish:
- ps: >-
    If (Test-Path .\xunit-report.xml) {
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit-report.xml))
    }
