# version format
version: "1.1.0-{build}"

# branches to build
branches:
  only:
    - master

# Operating system (build VM template)
os: Windows Server 2012 R2

# environment variables
environment:
  GOPATH: c:\gopath

# do not indent -ps!
init:
- ps: >-
    $app = Get-WmiObject -Class Win32_Product -Filter "Vendor = 'http://golang.org'"

    if ($app) {
      $app.Uninstall()
    }

# scripts that run after cloning repository
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.4.2.windows-amd64.msi
  - msiexec /i go1.4.2.windows-amd64.msi /q
  - go version
  - go env
  - mkdir c:\gopath
  - go get -u golang.org/x/tools/cmd/cover
  
# to run your custom scripts instead of automatic MSBuild
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - SET PATH=%GOPATH%\bin;%PATH%
  - go build

# to disable automatic tests
test_script:
  - go test -cover

# to disable deployment
deploy: off
