branches:
  only:
    - master

image: Visual Studio 2019

environment:
  GOPATH: c:\gopath
  GO111MODULE: on
  GOPROXY: https://proxy.golang.org  

init:
  - SET PATH=%GOPATH%\bin;%PATH%
  - git config --global core.autocrlf input

install:
  - go version
  - go env
  - go install github.com/tischda/go2xunit@latest
  - go get -d github.com/tischda/gotimer/registry

build_script:
  - for /f "delims=" %%a in ('git describe --tags') do @set version=%%a
  - ps: Update-AppveyorBuild -Version $env:version
  - go build -mod vendor -ldflags=all="-X main.version=%version% -s -w"

test_script:
  - gotimer.exe -version
  - go test -v -cover
  - go test -v | go2xunit.exe -xunitnet > xunit-report.xml
  - gotimer.exe start t1
  - gotimer.exe read t1
  - gotimer.exe start t2
  - gotimer.exe list
  - gotimer.exe stop t1
  - gotimer.exe clear
  - gotimer.exe exec "dir *.exe"

artifacts:
  - path: gotimer.exe
    name: Timer

deploy: off

on_finish:
- ps: >-
    If (Test-Path .\xunit-report.xml) {
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit-report.xml))
    }
