branches:
  only:
    - master

os: Windows Server 2012 R2

environment:
  GOPATH: c:\gopath

init:
  - SET PATH=%GOPATH%\bin;%PATH%
  - git config --global core.autocrlf input

install:
  - go version
  - go env
  - mkdir %GOPATH%
  - go get -u github.com/tischda/go2xunit
  - go get -u github.com/tischda/timer/registry

build_script:
  - for /f "delims=" %%a in ('git describe --tags') do @set version=%%a
  - ps: Update-AppveyorBuild -Version $env:version
  - go build -ldflags "-X main.version %version% -s"

test_script:
  - timer.exe -version
  - go test -v -cover
  - go test -v | go2xunit -xunitnet > xunit-report.xml
  - timer.exe start t1
  - timer.exe read t1
  - timer.exe start t2
  - timer.exe list
  - timer.exe stop t1
  - timer.exe clear
  - timer.exe exec "dir *.exe"

artifacts:
  - path: timer.exe
    name: Timer

deploy: off

on_finish:
- ps: >-
    If (Test-Path .\xunit-report.xml) {
      (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit-report.xml))
    }
